spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_playground
    username: user
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto:  update

